site_name: "GitHub Issue Resolution MCP Server"
site_description: "A comprehensive Model Context Protocol server for AI-powered GitHub issue analysis and resolution using advanced RAG techniques."
site_author: "GitHub Issue MCP Team"
site_url: "https://devdattatalele.github.io/github-issue-mcp-server/"

repo_name: "devdattatalele/github-issue-mcp-server"
repo_url: "https://github.com/devdattatalele/github-issue-mcp-server"

theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: 'index.md'
  - 'Getting Started':
    - 'Quick Start': 'getting_started/quickstart.md'
    - 'Installation': 'getting_started/installation.md'
    - 'Configuration': 'getting_started/configuration.md'
    - 'Claude Desktop Setup': 'getting_started/claude_setup.md'
  - 'Core Concepts':
    - 'MCP Overview': 'concepts/mcp_overview.md'
    - 'Architecture': 'concepts/architecture.md'
    - 'RAG System': 'concepts/rag_system.md'
    - 'Workflow': 'concepts/workflow.md'
  - 'Usage Guide':
    - 'Repository Ingestion': 'usage/ingestion.md'
    - 'Issue Analysis': 'usage/analysis.md'
    - 'Patch Generation': 'usage/patching.md'
    - 'Multi-Repository': 'usage/multi_repo.md'
    - 'Advanced Features': 'usage/advanced.md'
  - 'API Reference':
    - 'MCP Server': 'api_reference/server.md'
    - 'Ingest Module': 'api_reference/ingest.md'
    - 'Analyze Module': 'api_reference/analyze.md'
    - 'Patch Module': 'api_reference/patch.md'
    - 'Tools Reference': 'api_reference/tools.md'
  - 'Examples':
    - 'Basic Usage': 'examples/basic_usage.md'
    - 'Advanced Workflows': 'examples/advanced_workflows.md'
    - 'Integration Examples': 'examples/integrations.md'
  - 'Troubleshooting':
    - 'Common Issues': 'troubleshooting/common_issues.md'
    - 'Performance': 'troubleshooting/performance.md'
    - 'Debugging': 'troubleshooting/debugging.md'
  - 'Contributing':
    - 'Development Guide': 'contributing/development.md'
    - 'Testing': 'contributing/testing.md'
    - 'Documentation': 'contributing/documentation.md'

plugins:
  - search
  - macros 