site_name: "GitHub Issue Solver"
site_description: "An AI-powered system to analyze and resolve GitHub issues."
site_author: "Your Name"
site_url: "https://your-repo-url.com/"

repo_name: "your-github/issue-solver"
repo_url: "https://github.com/your-github/issue-solver"

theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: 'index.md'
  - 'Core Concepts':
    - 'Workflow': 'concepts/workflow.md'
    - 'Architecture': 'concepts/architecture.md'
  - 'Getting Started':
    - 'Installation': 'getting_started/installation.md'
    - 'Configuration': 'getting_started/configuration.md'
  - 'Usage':
    - 'Ingesting a Repository': 'usage/ingestion.md'
    - 'Analyzing an Issue': 'usage/analysis.md'
    - 'Generating Patches': 'usage/patching.md'
    - 'Running the Client': 'usage/client.md'
  - 'API Reference':
    - 'Analyze': 'api_reference/analyze.md'
    - 'Ingest': 'api_reference/ingest.md'
    - 'Patch': 'api_reference/patch.md'
    - 'Server': 'api_reference/server.md'

plugins:
  - search
  - macros 